//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace XTraTech.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class XTraTechEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new XTraTechEntities object using the connection string found in the 'XTraTechEntities' section of the application configuration file.
        /// </summary>
        public XTraTechEntities() : base("name=XTraTechEntities", "XTraTechEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new XTraTechEntities object.
        /// </summary>
        public XTraTechEntities(string connectionString) : base(connectionString, "XTraTechEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new XTraTechEntities object.
        /// </summary>
        public XTraTechEntities(EntityConnection connection) : base(connection, "XTraTechEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FlightDetail> FlightDetails
        {
            get
            {
                if ((_FlightDetails == null))
                {
                    _FlightDetails = base.CreateObjectSet<FlightDetail>("FlightDetails");
                }
                return _FlightDetails;
            }
        }
        private ObjectSet<FlightDetail> _FlightDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FlightFare> FlightFares
        {
            get
            {
                if ((_FlightFares == null))
                {
                    _FlightFares = base.CreateObjectSet<FlightFare>("FlightFares");
                }
                return _FlightFares;
            }
        }
        private ObjectSet<FlightFare> _FlightFares;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FlightPassenger> FlightPassengers
        {
            get
            {
                if ((_FlightPassengers == null))
                {
                    _FlightPassengers = base.CreateObjectSet<FlightPassenger>("FlightPassengers");
                }
                return _FlightPassengers;
            }
        }
        private ObjectSet<FlightPassenger> _FlightPassengers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FlightSegment> FlightSegments
        {
            get
            {
                if ((_FlightSegments == null))
                {
                    _FlightSegments = base.CreateObjectSet<FlightSegment>("FlightSegments");
                }
                return _FlightSegments;
            }
        }
        private ObjectSet<FlightSegment> _FlightSegments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Itinerary> Itineraries
        {
            get
            {
                if ((_Itineraries == null))
                {
                    _Itineraries = base.CreateObjectSet<Itinerary>("Itineraries");
                }
                return _Itineraries;
            }
        }
        private ObjectSet<Itinerary> _Itineraries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PurchaseOrder> PurchaseOrders
        {
            get
            {
                if ((_PurchaseOrders == null))
                {
                    _PurchaseOrders = base.CreateObjectSet<PurchaseOrder>("PurchaseOrders");
                }
                return _PurchaseOrders;
            }
        }
        private ObjectSet<PurchaseOrder> _PurchaseOrders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Airport> Airports
        {
            get
            {
                if ((_Airports == null))
                {
                    _Airports = base.CreateObjectSet<Airport>("Airports");
                }
                return _Airports;
            }
        }
        private ObjectSet<Airport> _Airports;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FlightDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFlightDetails(FlightDetail flightDetail)
        {
            base.AddObject("FlightDetails", flightDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FlightFares EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFlightFares(FlightFare flightFare)
        {
            base.AddObject("FlightFares", flightFare);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FlightPassengers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFlightPassengers(FlightPassenger flightPassenger)
        {
            base.AddObject("FlightPassengers", flightPassenger);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FlightSegments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFlightSegments(FlightSegment flightSegment)
        {
            base.AddObject("FlightSegments", flightSegment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Itineraries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItineraries(Itinerary itinerary)
        {
            base.AddObject("Itineraries", itinerary);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PurchaseOrders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPurchaseOrders(PurchaseOrder purchaseOrder)
        {
            base.AddObject("PurchaseOrders", purchaseOrder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Airports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAirports(Airport airport)
        {
            base.AddObject("Airports", airport);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XTraTechModel", Name="Airport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Airport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Airport object.
        /// </summary>
        /// <param name="airportCode">Initial value of the airportCode property.</param>
        /// <param name="langCode">Initial value of the LangCode property.</param>
        /// <param name="airpirtid">Initial value of the airpirtid property.</param>
        public static Airport CreateAirport(global::System.String airportCode, global::System.String langCode, global::System.Int64 airpirtid)
        {
            Airport airport = new Airport();
            airport.airportCode = airportCode;
            airport.LangCode = langCode;
            airport.airpirtid = airpirtid;
            return airport;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String airportCode
        {
            get
            {
                return _airportCode;
            }
            set
            {
                OnairportCodeChanging(value);
                ReportPropertyChanging("airportCode");
                _airportCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("airportCode");
                OnairportCodeChanged();
            }
        }
        private global::System.String _airportCode;
        partial void OnairportCodeChanging(global::System.String value);
        partial void OnairportCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String airportName
        {
            get
            {
                return _airportName;
            }
            set
            {
                OnairportNameChanging(value);
                ReportPropertyChanging("airportName");
                _airportName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("airportName");
                OnairportNameChanged();
            }
        }
        private global::System.String _airportName;
        partial void OnairportNameChanging(global::System.String value);
        partial void OnairportNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cityCode
        {
            get
            {
                return _cityCode;
            }
            set
            {
                OncityCodeChanging(value);
                ReportPropertyChanging("cityCode");
                _cityCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cityCode");
                OncityCodeChanged();
            }
        }
        private global::System.String _cityCode;
        partial void OncityCodeChanging(global::System.String value);
        partial void OncityCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cityName
        {
            get
            {
                return _cityName;
            }
            set
            {
                OncityNameChanging(value);
                ReportPropertyChanging("cityName");
                _cityName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cityName");
                OncityNameChanged();
            }
        }
        private global::System.String _cityName;
        partial void OncityNameChanging(global::System.String value);
        partial void OncityNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String countryName
        {
            get
            {
                return _countryName;
            }
            set
            {
                OncountryNameChanging(value);
                ReportPropertyChanging("countryName");
                _countryName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("countryName");
                OncountryNameChanged();
            }
        }
        private global::System.String _countryName;
        partial void OncountryNameChanging(global::System.String value);
        partial void OncountryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String countryCode
        {
            get
            {
                return _countryCode;
            }
            set
            {
                OncountryCodeChanging(value);
                ReportPropertyChanging("countryCode");
                _countryCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("countryCode");
                OncountryCodeChanged();
            }
        }
        private global::System.String _countryCode;
        partial void OncountryCodeChanging(global::System.String value);
        partial void OncountryCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LangCode
        {
            get
            {
                return _LangCode;
            }
            set
            {
                OnLangCodeChanging(value);
                ReportPropertyChanging("LangCode");
                _LangCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LangCode");
                OnLangCodeChanged();
            }
        }
        private global::System.String _LangCode;
        partial void OnLangCodeChanging(global::System.String value);
        partial void OnLangCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ICAO
        {
            get
            {
                return _ICAO;
            }
            set
            {
                OnICAOChanging(value);
                ReportPropertyChanging("ICAO");
                _ICAO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ICAO");
                OnICAOChanged();
            }
        }
        private global::System.String _ICAO;
        partial void OnICAOChanging(global::System.String value);
        partial void OnICAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String latitude
        {
            get
            {
                return _latitude;
            }
            set
            {
                OnlatitudeChanging(value);
                ReportPropertyChanging("latitude");
                _latitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("latitude");
                OnlatitudeChanged();
            }
        }
        private global::System.String _latitude;
        partial void OnlatitudeChanging(global::System.String value);
        partial void OnlatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String longitude
        {
            get
            {
                return _longitude;
            }
            set
            {
                OnlongitudeChanging(value);
                ReportPropertyChanging("longitude");
                _longitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("longitude");
                OnlongitudeChanged();
            }
        }
        private global::System.String _longitude;
        partial void OnlongitudeChanging(global::System.String value);
        partial void OnlongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String altitude
        {
            get
            {
                return _altitude;
            }
            set
            {
                OnaltitudeChanging(value);
                ReportPropertyChanging("altitude");
                _altitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("altitude");
                OnaltitudeChanged();
            }
        }
        private global::System.String _altitude;
        partial void OnaltitudeChanging(global::System.String value);
        partial void OnaltitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String timezone
        {
            get
            {
                return _timezone;
            }
            set
            {
                OntimezoneChanging(value);
                ReportPropertyChanging("timezone");
                _timezone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timezone");
                OntimezoneChanged();
            }
        }
        private global::System.String _timezone;
        partial void OntimezoneChanging(global::System.String value);
        partial void OntimezoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DST
        {
            get
            {
                return _DST;
            }
            set
            {
                OnDSTChanging(value);
                ReportPropertyChanging("DST");
                _DST = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DST");
                OnDSTChanged();
            }
        }
        private global::System.String _DST;
        partial void OnDSTChanging(global::System.String value);
        partial void OnDSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UTCOffset
        {
            get
            {
                return _UTCOffset;
            }
            set
            {
                OnUTCOffsetChanging(value);
                ReportPropertyChanging("UTCOffset");
                _UTCOffset = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UTCOffset");
                OnUTCOffsetChanged();
            }
        }
        private global::System.String _UTCOffset;
        partial void OnUTCOffsetChanging(global::System.String value);
        partial void OnUTCOffsetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 airpirtid
        {
            get
            {
                return _airpirtid;
            }
            set
            {
                if (_airpirtid != value)
                {
                    OnairpirtidChanging(value);
                    ReportPropertyChanging("airpirtid");
                    _airpirtid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("airpirtid");
                    OnairpirtidChanged();
                }
            }
        }
        private global::System.Int64 _airpirtid;
        partial void OnairpirtidChanging(global::System.Int64 value);
        partial void OnairpirtidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XTraTechModel", Name="FlightDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FlightDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FlightDetail object.
        /// </summary>
        /// <param name="flightDetailsID">Initial value of the FlightDetailsID property.</param>
        /// <param name="purchaseOrderID">Initial value of the PurchaseOrderID property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        /// <param name="modefiedOn">Initial value of the ModefiedOn property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="itineraryID">Initial value of the ItineraryID property.</param>
        public static FlightDetail CreateFlightDetail(global::System.Int64 flightDetailsID, global::System.Int64 purchaseOrderID, global::System.DateTime createdOn, global::System.DateTime modefiedOn, global::System.Int32 status, global::System.String itineraryID)
        {
            FlightDetail flightDetail = new FlightDetail();
            flightDetail.FlightDetailsID = flightDetailsID;
            flightDetail.PurchaseOrderID = purchaseOrderID;
            flightDetail.CreatedOn = createdOn;
            flightDetail.ModefiedOn = modefiedOn;
            flightDetail.Status = status;
            flightDetail.ItineraryID = itineraryID;
            return flightDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FlightDetailsID
        {
            get
            {
                return _FlightDetailsID;
            }
            set
            {
                if (_FlightDetailsID != value)
                {
                    OnFlightDetailsIDChanging(value);
                    ReportPropertyChanging("FlightDetailsID");
                    _FlightDetailsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FlightDetailsID");
                    OnFlightDetailsIDChanged();
                }
            }
        }
        private global::System.Int64 _FlightDetailsID;
        partial void OnFlightDetailsIDChanging(global::System.Int64 value);
        partial void OnFlightDetailsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PurchaseOrderID
        {
            get
            {
                return _PurchaseOrderID;
            }
            set
            {
                OnPurchaseOrderIDChanging(value);
                ReportPropertyChanging("PurchaseOrderID");
                _PurchaseOrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PurchaseOrderID");
                OnPurchaseOrderIDChanged();
            }
        }
        private global::System.Int64 _PurchaseOrderID;
        partial void OnPurchaseOrderIDChanging(global::System.Int64 value);
        partial void OnPurchaseOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TktTimeLimit
        {
            get
            {
                return _TktTimeLimit;
            }
            set
            {
                OnTktTimeLimitChanging(value);
                ReportPropertyChanging("TktTimeLimit");
                _TktTimeLimit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TktTimeLimit");
                OnTktTimeLimitChanged();
            }
        }
        private Nullable<global::System.DateTime> _TktTimeLimit;
        partial void OnTktTimeLimitChanging(Nullable<global::System.DateTime> value);
        partial void OnTktTimeLimitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModefiedOn
        {
            get
            {
                return _ModefiedOn;
            }
            set
            {
                OnModefiedOnChanging(value);
                ReportPropertyChanging("ModefiedOn");
                _ModefiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModefiedOn");
                OnModefiedOnChanged();
            }
        }
        private global::System.DateTime _ModefiedOn;
        partial void OnModefiedOnChanging(global::System.DateTime value);
        partial void OnModefiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PNR
        {
            get
            {
                return _PNR;
            }
            set
            {
                OnPNRChanging(value);
                ReportPropertyChanging("PNR");
                _PNR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PNR");
                OnPNRChanged();
            }
        }
        private global::System.String _PNR;
        partial void OnPNRChanging(global::System.String value);
        partial void OnPNRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItineraryID
        {
            get
            {
                return _ItineraryID;
            }
            set
            {
                OnItineraryIDChanging(value);
                ReportPropertyChanging("ItineraryID");
                _ItineraryID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItineraryID");
                OnItineraryIDChanged();
            }
        }
        private global::System.String _ItineraryID;
        partial void OnItineraryIDChanging(global::System.String value);
        partial void OnItineraryIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XTraTechModel", Name="FlightFare")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FlightFare : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FlightFare object.
        /// </summary>
        /// <param name="flightFareID">Initial value of the FlightFareID property.</param>
        /// <param name="flightDetailsID">Initial value of the FlightDetailsID property.</param>
        /// <param name="baseFare">Initial value of the BaseFare property.</param>
        /// <param name="tax">Initial value of the Tax property.</param>
        /// <param name="currency">Initial value of the Currency property.</param>
        /// <param name="rOE">Initial value of the ROE property.</param>
        /// <param name="paxType">Initial value of the PaxType property.</param>
        /// <param name="paxCount">Initial value of the PaxCount property.</param>
        /// <param name="markUp">Initial value of the MarkUp property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        /// <param name="modefiedOn">Initial value of the ModefiedOn property.</param>
        /// <param name="fareType">Initial value of the FareType property.</param>
        public static FlightFare CreateFlightFare(global::System.Int64 flightFareID, global::System.Int64 flightDetailsID, global::System.Decimal baseFare, global::System.Decimal tax, global::System.String currency, global::System.Decimal rOE, global::System.Byte paxType, global::System.Byte paxCount, global::System.Decimal markUp, global::System.DateTime createdOn, global::System.DateTime modefiedOn, global::System.String fareType)
        {
            FlightFare flightFare = new FlightFare();
            flightFare.FlightFareID = flightFareID;
            flightFare.FlightDetailsID = flightDetailsID;
            flightFare.BaseFare = baseFare;
            flightFare.Tax = tax;
            flightFare.Currency = currency;
            flightFare.ROE = rOE;
            flightFare.PaxType = paxType;
            flightFare.PaxCount = paxCount;
            flightFare.MarkUp = markUp;
            flightFare.CreatedOn = createdOn;
            flightFare.ModefiedOn = modefiedOn;
            flightFare.FareType = fareType;
            return flightFare;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FlightFareID
        {
            get
            {
                return _FlightFareID;
            }
            set
            {
                if (_FlightFareID != value)
                {
                    OnFlightFareIDChanging(value);
                    ReportPropertyChanging("FlightFareID");
                    _FlightFareID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FlightFareID");
                    OnFlightFareIDChanged();
                }
            }
        }
        private global::System.Int64 _FlightFareID;
        partial void OnFlightFareIDChanging(global::System.Int64 value);
        partial void OnFlightFareIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FlightDetailsID
        {
            get
            {
                return _FlightDetailsID;
            }
            set
            {
                OnFlightDetailsIDChanging(value);
                ReportPropertyChanging("FlightDetailsID");
                _FlightDetailsID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlightDetailsID");
                OnFlightDetailsIDChanged();
            }
        }
        private global::System.Int64 _FlightDetailsID;
        partial void OnFlightDetailsIDChanging(global::System.Int64 value);
        partial void OnFlightDetailsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal BaseFare
        {
            get
            {
                return _BaseFare;
            }
            set
            {
                OnBaseFareChanging(value);
                ReportPropertyChanging("BaseFare");
                _BaseFare = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BaseFare");
                OnBaseFareChanged();
            }
        }
        private global::System.Decimal _BaseFare;
        partial void OnBaseFareChanging(global::System.Decimal value);
        partial void OnBaseFareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Tax
        {
            get
            {
                return _Tax;
            }
            set
            {
                OnTaxChanging(value);
                ReportPropertyChanging("Tax");
                _Tax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tax");
                OnTaxChanged();
            }
        }
        private global::System.Decimal _Tax;
        partial void OnTaxChanging(global::System.Decimal value);
        partial void OnTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ROE
        {
            get
            {
                return _ROE;
            }
            set
            {
                OnROEChanging(value);
                ReportPropertyChanging("ROE");
                _ROE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ROE");
                OnROEChanged();
            }
        }
        private global::System.Decimal _ROE;
        partial void OnROEChanging(global::System.Decimal value);
        partial void OnROEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte PaxType
        {
            get
            {
                return _PaxType;
            }
            set
            {
                OnPaxTypeChanging(value);
                ReportPropertyChanging("PaxType");
                _PaxType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaxType");
                OnPaxTypeChanged();
            }
        }
        private global::System.Byte _PaxType;
        partial void OnPaxTypeChanging(global::System.Byte value);
        partial void OnPaxTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte PaxCount
        {
            get
            {
                return _PaxCount;
            }
            set
            {
                OnPaxCountChanging(value);
                ReportPropertyChanging("PaxCount");
                _PaxCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaxCount");
                OnPaxCountChanged();
            }
        }
        private global::System.Byte _PaxCount;
        partial void OnPaxCountChanging(global::System.Byte value);
        partial void OnPaxCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MarkUp
        {
            get
            {
                return _MarkUp;
            }
            set
            {
                OnMarkUpChanging(value);
                ReportPropertyChanging("MarkUp");
                _MarkUp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MarkUp");
                OnMarkUpChanged();
            }
        }
        private global::System.Decimal _MarkUp;
        partial void OnMarkUpChanging(global::System.Decimal value);
        partial void OnMarkUpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModefiedOn
        {
            get
            {
                return _ModefiedOn;
            }
            set
            {
                OnModefiedOnChanging(value);
                ReportPropertyChanging("ModefiedOn");
                _ModefiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModefiedOn");
                OnModefiedOnChanged();
            }
        }
        private global::System.DateTime _ModefiedOn;
        partial void OnModefiedOnChanging(global::System.DateTime value);
        partial void OnModefiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FareType
        {
            get
            {
                return _FareType;
            }
            set
            {
                OnFareTypeChanging(value);
                ReportPropertyChanging("FareType");
                _FareType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FareType");
                OnFareTypeChanged();
            }
        }
        private global::System.String _FareType;
        partial void OnFareTypeChanging(global::System.String value);
        partial void OnFareTypeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XTraTechModel", Name="FlightPassenger")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FlightPassenger : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FlightPassenger object.
        /// </summary>
        /// <param name="paxID">Initial value of the PaxID property.</param>
        /// <param name="purchaseOrderID">Initial value of the PurchaseOrderID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="paxType">Initial value of the PaxType property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        /// <param name="modefiedOn">Initial value of the ModefiedOn property.</param>
        public static FlightPassenger CreateFlightPassenger(global::System.Int64 paxID, global::System.Int64 purchaseOrderID, global::System.String title, global::System.String firstName, global::System.String lastName, global::System.String gender, global::System.Byte paxType, global::System.DateTime createdOn, global::System.DateTime modefiedOn)
        {
            FlightPassenger flightPassenger = new FlightPassenger();
            flightPassenger.PaxID = paxID;
            flightPassenger.PurchaseOrderID = purchaseOrderID;
            flightPassenger.Title = title;
            flightPassenger.FirstName = firstName;
            flightPassenger.LastName = lastName;
            flightPassenger.Gender = gender;
            flightPassenger.PaxType = paxType;
            flightPassenger.CreatedOn = createdOn;
            flightPassenger.ModefiedOn = modefiedOn;
            return flightPassenger;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PaxID
        {
            get
            {
                return _PaxID;
            }
            set
            {
                if (_PaxID != value)
                {
                    OnPaxIDChanging(value);
                    ReportPropertyChanging("PaxID");
                    _PaxID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaxID");
                    OnPaxIDChanged();
                }
            }
        }
        private global::System.Int64 _PaxID;
        partial void OnPaxIDChanging(global::System.Int64 value);
        partial void OnPaxIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PurchaseOrderID
        {
            get
            {
                return _PurchaseOrderID;
            }
            set
            {
                OnPurchaseOrderIDChanging(value);
                ReportPropertyChanging("PurchaseOrderID");
                _PurchaseOrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PurchaseOrderID");
                OnPurchaseOrderIDChanged();
            }
        }
        private global::System.Int64 _PurchaseOrderID;
        partial void OnPurchaseOrderIDChanging(global::System.Int64 value);
        partial void OnPurchaseOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AreaCode
        {
            get
            {
                return _AreaCode;
            }
            set
            {
                OnAreaCodeChanging(value);
                ReportPropertyChanging("AreaCode");
                _AreaCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AreaCode");
                OnAreaCodeChanged();
            }
        }
        private global::System.String _AreaCode;
        partial void OnAreaCodeChanging(global::System.String value);
        partial void OnAreaCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountryCode
        {
            get
            {
                return _CountryCode;
            }
            set
            {
                OnCountryCodeChanging(value);
                ReportPropertyChanging("CountryCode");
                _CountryCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CountryCode");
                OnCountryCodeChanged();
            }
        }
        private global::System.String _CountryCode;
        partial void OnCountryCodeChanging(global::System.String value);
        partial void OnCountryCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FFNumber
        {
            get
            {
                return _FFNumber;
            }
            set
            {
                OnFFNumberChanging(value);
                ReportPropertyChanging("FFNumber");
                _FFNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FFNumber");
                OnFFNumberChanged();
            }
        }
        private global::System.String _FFNumber;
        partial void OnFFNumberChanging(global::System.String value);
        partial void OnFFNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte PaxType
        {
            get
            {
                return _PaxType;
            }
            set
            {
                OnPaxTypeChanging(value);
                ReportPropertyChanging("PaxType");
                _PaxType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaxType");
                OnPaxTypeChanged();
            }
        }
        private global::System.Byte _PaxType;
        partial void OnPaxTypeChanging(global::System.Byte value);
        partial void OnPaxTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PassportNumber
        {
            get
            {
                return _PassportNumber;
            }
            set
            {
                OnPassportNumberChanging(value);
                ReportPropertyChanging("PassportNumber");
                _PassportNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PassportNumber");
                OnPassportNumberChanged();
            }
        }
        private global::System.String _PassportNumber;
        partial void OnPassportNumberChanging(global::System.String value);
        partial void OnPassportNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PassportDOE
        {
            get
            {
                return _PassportDOE;
            }
            set
            {
                OnPassportDOEChanging(value);
                ReportPropertyChanging("PassportDOE");
                _PassportDOE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PassportDOE");
                OnPassportDOEChanged();
            }
        }
        private Nullable<global::System.DateTime> _PassportDOE;
        partial void OnPassportDOEChanging(Nullable<global::System.DateTime> value);
        partial void OnPassportDOEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PassportNationality
        {
            get
            {
                return _PassportNationality;
            }
            set
            {
                OnPassportNationalityChanging(value);
                ReportPropertyChanging("PassportNationality");
                _PassportNationality = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PassportNationality");
                OnPassportNationalityChanged();
            }
        }
        private global::System.String _PassportNationality;
        partial void OnPassportNationalityChanging(global::System.String value);
        partial void OnPassportNationalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> SeatPref
        {
            get
            {
                return _SeatPref;
            }
            set
            {
                OnSeatPrefChanging(value);
                ReportPropertyChanging("SeatPref");
                _SeatPref = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeatPref");
                OnSeatPrefChanged();
            }
        }
        private Nullable<global::System.Byte> _SeatPref;
        partial void OnSeatPrefChanging(Nullable<global::System.Byte> value);
        partial void OnSeatPrefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> MealPref
        {
            get
            {
                return _MealPref;
            }
            set
            {
                OnMealPrefChanging(value);
                ReportPropertyChanging("MealPref");
                _MealPref = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MealPref");
                OnMealPrefChanged();
            }
        }
        private Nullable<global::System.Byte> _MealPref;
        partial void OnMealPrefChanging(Nullable<global::System.Byte> value);
        partial void OnMealPrefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModefiedOn
        {
            get
            {
                return _ModefiedOn;
            }
            set
            {
                OnModefiedOnChanging(value);
                ReportPropertyChanging("ModefiedOn");
                _ModefiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModefiedOn");
                OnModefiedOnChanged();
            }
        }
        private global::System.DateTime _ModefiedOn;
        partial void OnModefiedOnChanging(global::System.DateTime value);
        partial void OnModefiedOnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XTraTechModel", Name="FlightSegment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FlightSegment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FlightSegment object.
        /// </summary>
        /// <param name="flightSegmentID">Initial value of the FlightSegmentID property.</param>
        /// <param name="flightDetailsID">Initial value of the FlightDetailsID property.</param>
        /// <param name="origin">Initial value of the Origin property.</param>
        /// <param name="destination">Initial value of the Destination property.</param>
        /// <param name="departureDateTime">Initial value of the DepartureDateTime property.</param>
        /// <param name="arrivalDateime">Initial value of the ArrivalDateime property.</param>
        /// <param name="flightNumber">Initial value of the FlightNumber property.</param>
        /// <param name="flightCode">Initial value of the FlightCode property.</param>
        /// <param name="operatingAirline">Initial value of the OperatingAirline property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        /// <param name="modefiedOn">Initial value of the ModefiedOn property.</param>
        /// <param name="isReturn">Initial value of the IsReturn property.</param>
        public static FlightSegment CreateFlightSegment(global::System.Int64 flightSegmentID, global::System.Int64 flightDetailsID, global::System.String origin, global::System.String destination, global::System.DateTime departureDateTime, global::System.DateTime arrivalDateime, global::System.String flightNumber, global::System.String flightCode, global::System.String operatingAirline, global::System.DateTime createdOn, global::System.DateTime modefiedOn, global::System.Boolean isReturn)
        {
            FlightSegment flightSegment = new FlightSegment();
            flightSegment.FlightSegmentID = flightSegmentID;
            flightSegment.FlightDetailsID = flightDetailsID;
            flightSegment.Origin = origin;
            flightSegment.Destination = destination;
            flightSegment.DepartureDateTime = departureDateTime;
            flightSegment.ArrivalDateime = arrivalDateime;
            flightSegment.FlightNumber = flightNumber;
            flightSegment.FlightCode = flightCode;
            flightSegment.OperatingAirline = operatingAirline;
            flightSegment.CreatedOn = createdOn;
            flightSegment.ModefiedOn = modefiedOn;
            flightSegment.IsReturn = isReturn;
            return flightSegment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FlightSegmentID
        {
            get
            {
                return _FlightSegmentID;
            }
            set
            {
                if (_FlightSegmentID != value)
                {
                    OnFlightSegmentIDChanging(value);
                    ReportPropertyChanging("FlightSegmentID");
                    _FlightSegmentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FlightSegmentID");
                    OnFlightSegmentIDChanged();
                }
            }
        }
        private global::System.Int64 _FlightSegmentID;
        partial void OnFlightSegmentIDChanging(global::System.Int64 value);
        partial void OnFlightSegmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FlightDetailsID
        {
            get
            {
                return _FlightDetailsID;
            }
            set
            {
                OnFlightDetailsIDChanging(value);
                ReportPropertyChanging("FlightDetailsID");
                _FlightDetailsID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlightDetailsID");
                OnFlightDetailsIDChanged();
            }
        }
        private global::System.Int64 _FlightDetailsID;
        partial void OnFlightDetailsIDChanging(global::System.Int64 value);
        partial void OnFlightDetailsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Origin
        {
            get
            {
                return _Origin;
            }
            set
            {
                OnOriginChanging(value);
                ReportPropertyChanging("Origin");
                _Origin = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Origin");
                OnOriginChanged();
            }
        }
        private global::System.String _Origin;
        partial void OnOriginChanging(global::System.String value);
        partial void OnOriginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Destination
        {
            get
            {
                return _Destination;
            }
            set
            {
                OnDestinationChanging(value);
                ReportPropertyChanging("Destination");
                _Destination = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Destination");
                OnDestinationChanged();
            }
        }
        private global::System.String _Destination;
        partial void OnDestinationChanging(global::System.String value);
        partial void OnDestinationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DepartureDateTime
        {
            get
            {
                return _DepartureDateTime;
            }
            set
            {
                OnDepartureDateTimeChanging(value);
                ReportPropertyChanging("DepartureDateTime");
                _DepartureDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartureDateTime");
                OnDepartureDateTimeChanged();
            }
        }
        private global::System.DateTime _DepartureDateTime;
        partial void OnDepartureDateTimeChanging(global::System.DateTime value);
        partial void OnDepartureDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ArrivalDateime
        {
            get
            {
                return _ArrivalDateime;
            }
            set
            {
                OnArrivalDateimeChanging(value);
                ReportPropertyChanging("ArrivalDateime");
                _ArrivalDateime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ArrivalDateime");
                OnArrivalDateimeChanged();
            }
        }
        private global::System.DateTime _ArrivalDateime;
        partial void OnArrivalDateimeChanging(global::System.DateTime value);
        partial void OnArrivalDateimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JourneyDuration
        {
            get
            {
                return _JourneyDuration;
            }
            set
            {
                OnJourneyDurationChanging(value);
                ReportPropertyChanging("JourneyDuration");
                _JourneyDuration = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JourneyDuration");
                OnJourneyDurationChanged();
            }
        }
        private global::System.String _JourneyDuration;
        partial void OnJourneyDurationChanging(global::System.String value);
        partial void OnJourneyDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StopQuantity
        {
            get
            {
                return _StopQuantity;
            }
            set
            {
                OnStopQuantityChanging(value);
                ReportPropertyChanging("StopQuantity");
                _StopQuantity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StopQuantity");
                OnStopQuantityChanged();
            }
        }
        private global::System.String _StopQuantity;
        partial void OnStopQuantityChanging(global::System.String value);
        partial void OnStopQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FlightNumber
        {
            get
            {
                return _FlightNumber;
            }
            set
            {
                OnFlightNumberChanging(value);
                ReportPropertyChanging("FlightNumber");
                _FlightNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FlightNumber");
                OnFlightNumberChanged();
            }
        }
        private global::System.String _FlightNumber;
        partial void OnFlightNumberChanging(global::System.String value);
        partial void OnFlightNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FlightCode
        {
            get
            {
                return _FlightCode;
            }
            set
            {
                OnFlightCodeChanging(value);
                ReportPropertyChanging("FlightCode");
                _FlightCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FlightCode");
                OnFlightCodeChanged();
            }
        }
        private global::System.String _FlightCode;
        partial void OnFlightCodeChanging(global::System.String value);
        partial void OnFlightCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OperatingAirline
        {
            get
            {
                return _OperatingAirline;
            }
            set
            {
                OnOperatingAirlineChanging(value);
                ReportPropertyChanging("OperatingAirline");
                _OperatingAirline = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OperatingAirline");
                OnOperatingAirlineChanged();
            }
        }
        private global::System.String _OperatingAirline;
        partial void OnOperatingAirlineChanging(global::System.String value);
        partial void OnOperatingAirlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EquipmentType
        {
            get
            {
                return _EquipmentType;
            }
            set
            {
                OnEquipmentTypeChanging(value);
                ReportPropertyChanging("EquipmentType");
                _EquipmentType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EquipmentType");
                OnEquipmentTypeChanged();
            }
        }
        private global::System.String _EquipmentType;
        partial void OnEquipmentTypeChanging(global::System.String value);
        partial void OnEquipmentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BookingClass
        {
            get
            {
                return _BookingClass;
            }
            set
            {
                OnBookingClassChanging(value);
                ReportPropertyChanging("BookingClass");
                _BookingClass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BookingClass");
                OnBookingClassChanged();
            }
        }
        private global::System.String _BookingClass;
        partial void OnBookingClassChanging(global::System.String value);
        partial void OnBookingClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CabinClass
        {
            get
            {
                return _CabinClass;
            }
            set
            {
                OnCabinClassChanging(value);
                ReportPropertyChanging("CabinClass");
                _CabinClass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CabinClass");
                OnCabinClassChanged();
            }
        }
        private global::System.String _CabinClass;
        partial void OnCabinClassChanging(global::System.String value);
        partial void OnCabinClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MarketingAirline
        {
            get
            {
                return _MarketingAirline;
            }
            set
            {
                OnMarketingAirlineChanging(value);
                ReportPropertyChanging("MarketingAirline");
                _MarketingAirline = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MarketingAirline");
                OnMarketingAirlineChanged();
            }
        }
        private global::System.String _MarketingAirline;
        partial void OnMarketingAirlineChanging(global::System.String value);
        partial void OnMarketingAirlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AirlinePNR
        {
            get
            {
                return _AirlinePNR;
            }
            set
            {
                OnAirlinePNRChanging(value);
                ReportPropertyChanging("AirlinePNR");
                _AirlinePNR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AirlinePNR");
                OnAirlinePNRChanged();
            }
        }
        private global::System.String _AirlinePNR;
        partial void OnAirlinePNRChanging(global::System.String value);
        partial void OnAirlinePNRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModefiedOn
        {
            get
            {
                return _ModefiedOn;
            }
            set
            {
                OnModefiedOnChanging(value);
                ReportPropertyChanging("ModefiedOn");
                _ModefiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModefiedOn");
                OnModefiedOnChanged();
            }
        }
        private global::System.DateTime _ModefiedOn;
        partial void OnModefiedOnChanging(global::System.DateTime value);
        partial void OnModefiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SegmentGroupID
        {
            get
            {
                return _SegmentGroupID;
            }
            set
            {
                OnSegmentGroupIDChanging(value);
                ReportPropertyChanging("SegmentGroupID");
                _SegmentGroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SegmentGroupID");
                OnSegmentGroupIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SegmentGroupID;
        partial void OnSegmentGroupIDChanging(Nullable<global::System.Int32> value);
        partial void OnSegmentGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsReturn
        {
            get
            {
                return _IsReturn;
            }
            set
            {
                OnIsReturnChanging(value);
                ReportPropertyChanging("IsReturn");
                _IsReturn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReturn");
                OnIsReturnChanged();
            }
        }
        private global::System.Boolean _IsReturn;
        partial void OnIsReturnChanging(global::System.Boolean value);
        partial void OnIsReturnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XTraTechModel", Name="Itinerary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Itinerary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Itinerary object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="itineraryID">Initial value of the ItineraryID property.</param>
        /// <param name="serializedXML">Initial value of the SerializedXML property.</param>
        /// <param name="searchID">Initial value of the SearchID property.</param>
        public static Itinerary CreateItinerary(global::System.Int64 id, global::System.String itineraryID, global::System.Byte[] serializedXML, global::System.String searchID)
        {
            Itinerary itinerary = new Itinerary();
            itinerary.ID = id;
            itinerary.ItineraryID = itineraryID;
            itinerary.SerializedXML = serializedXML;
            itinerary.SearchID = searchID;
            return itinerary;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItineraryID
        {
            get
            {
                return _ItineraryID;
            }
            set
            {
                OnItineraryIDChanging(value);
                ReportPropertyChanging("ItineraryID");
                _ItineraryID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItineraryID");
                OnItineraryIDChanged();
            }
        }
        private global::System.String _ItineraryID;
        partial void OnItineraryIDChanging(global::System.String value);
        partial void OnItineraryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] SerializedXML
        {
            get
            {
                return StructuralObject.GetValidValue(_SerializedXML);
            }
            set
            {
                OnSerializedXMLChanging(value);
                ReportPropertyChanging("SerializedXML");
                _SerializedXML = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SerializedXML");
                OnSerializedXMLChanged();
            }
        }
        private global::System.Byte[] _SerializedXML;
        partial void OnSerializedXMLChanging(global::System.Byte[] value);
        partial void OnSerializedXMLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SearchID
        {
            get
            {
                return _SearchID;
            }
            set
            {
                OnSearchIDChanging(value);
                ReportPropertyChanging("SearchID");
                _SearchID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SearchID");
                OnSearchIDChanged();
            }
        }
        private global::System.String _SearchID;
        partial void OnSearchIDChanging(global::System.String value);
        partial void OnSearchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsBooked
        {
            get
            {
                return _IsBooked;
            }
            set
            {
                OnIsBookedChanging(value);
                ReportPropertyChanging("IsBooked");
                _IsBooked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBooked");
                OnIsBookedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsBooked;
        partial void OnIsBookedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsBookedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XTraTechModel", Name="PurchaseOrder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PurchaseOrder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PurchaseOrder object.
        /// </summary>
        /// <param name="purchaseOrderID">Initial value of the PurchaseOrderID property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        /// <param name="modefiedOn">Initial value of the ModefiedOn property.</param>
        /// <param name="clientID">Initial value of the ClientID property.</param>
        /// <param name="searchID">Initial value of the SearchID property.</param>
        public static PurchaseOrder CreatePurchaseOrder(global::System.Int64 purchaseOrderID, global::System.Int32 status, global::System.DateTime createdOn, global::System.DateTime modefiedOn, global::System.Int32 clientID, global::System.String searchID)
        {
            PurchaseOrder purchaseOrder = new PurchaseOrder();
            purchaseOrder.PurchaseOrderID = purchaseOrderID;
            purchaseOrder.Status = status;
            purchaseOrder.CreatedOn = createdOn;
            purchaseOrder.ModefiedOn = modefiedOn;
            purchaseOrder.ClientID = clientID;
            purchaseOrder.SearchID = searchID;
            return purchaseOrder;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PurchaseOrderID
        {
            get
            {
                return _PurchaseOrderID;
            }
            set
            {
                if (_PurchaseOrderID != value)
                {
                    OnPurchaseOrderIDChanging(value);
                    ReportPropertyChanging("PurchaseOrderID");
                    _PurchaseOrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PurchaseOrderID");
                    OnPurchaseOrderIDChanged();
                }
            }
        }
        private global::System.Int64 _PurchaseOrderID;
        partial void OnPurchaseOrderIDChanging(global::System.Int64 value);
        partial void OnPurchaseOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModefiedOn
        {
            get
            {
                return _ModefiedOn;
            }
            set
            {
                OnModefiedOnChanging(value);
                ReportPropertyChanging("ModefiedOn");
                _ModefiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModefiedOn");
                OnModefiedOnChanged();
            }
        }
        private global::System.DateTime _ModefiedOn;
        partial void OnModefiedOnChanging(global::System.DateTime value);
        partial void OnModefiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientID
        {
            get
            {
                return _ClientID;
            }
            set
            {
                OnClientIDChanging(value);
                ReportPropertyChanging("ClientID");
                _ClientID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientID");
                OnClientIDChanged();
            }
        }
        private global::System.Int32 _ClientID;
        partial void OnClientIDChanging(global::System.Int32 value);
        partial void OnClientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SearchID
        {
            get
            {
                return _SearchID;
            }
            set
            {
                OnSearchIDChanging(value);
                ReportPropertyChanging("SearchID");
                _SearchID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SearchID");
                OnSearchIDChanged();
            }
        }
        private global::System.String _SearchID;
        partial void OnSearchIDChanging(global::System.String value);
        partial void OnSearchIDChanged();

        #endregion

    
    }

    #endregion

    
}
